FROM openjdk:21-jdk
MAINTAINER Dima
COPY target/feedcollector-0.0.1-SNAPSHOT.jar app.jar
ARG DB_HOST=localhost
ARG DB_PORT=5432
ARG DB_NAME=feed_collector
ARG DB_USER=postgres
ARG DB_PASSWORD=123

ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]