version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=feedback_db
      - DB_USER=postgres
      - DB_PASSWORD=123
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
